<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><!DOCTYPE mql_results [
  <!ELEMENT mql_results (mql_result)* >
  <!ELEMENT mql_result ((mql_progress)?, status, (error)?, (warning)?, (table|sheaf|flatsheaf)?) >
  <!ELEMENT mql_progress (#PCDATA)* >
  <!ELEMENT status EMPTY >
  <!ELEMENT error (error_source, error_stage, 
                   error_message_db, error_message_compiler) >
  <!ELEMENT error_source EMPTY >
  <!ELEMENT error_stage EMPTY >
  <!ELEMENT error_message_db (#PCDATA)* >
  <!ELEMENT error_message_compiler (#PCDATA)* >
  <!ELEMENT warning (#PCDATA)* >
  <!ATTLIST mql_results >
  <!ATTLIST mql_result  >
  <!ATTLIST status 
                success (true|false) #REQUIRED >
  <!ATTLIST error >
  <!ATTLIST error_source 
                source  (compiler|db) #REQUIRED >
  <!ATTLIST error_stage  
                stage   (none|parse|weed|symbol|type|monads|exec) #REQUIRED >
  <!ATTLIST error_message_db >
  <!ATTLIST error_message_compiler >
  <!ATTLIST warning >
  <!ELEMENT table (theader, trow*) >
  <!ELEMENT theader (theadercolumn)* >
  <!ELEMENT theadercolumn (tcaption, ttype) >
  <!ELEMENT tcaption (#PCDATA)* >
  <!ELEMENT ttype EMPTY >
  <!ELEMENT trow (tcolumn)* >
  <!ELEMENT tcolumn (#PCDATA)* >
  <!ATTLIST table >
  <!ATTLIST theader >
  <!ATTLIST theadercolumn >
  <!ATTLIST tcaption >
  <!ATTLIST ttype 
     type (bool|string|integer|id_d|enum|list_of_integer|list_of_id_d|list_of_enum|set_of_monads) #REQUIRED
     enum_type CDATA #IMPLIED >
  <!ATTLIST trow >
  <!ATTLIST tcolumn >
  <!ELEMENT sheaf (straw)* >
  <!ELEMENT straw (matched_object)* >
  <!ELEMENT matched_object (monad_set, (features)?, (sheaf)?) >
  <!ELEMENT monad_set (mse)+ >
  <!ELEMENT mse EMPTY>
  <!ELEMENT features (feature)+ >
  <!ELEMENT feature (#PCDATA) >
  <!ATTLIST sheaf >
  <!ATTLIST straw >
  <!ATTLIST matched_object 
            object_type_name CDATA #REQUIRED 
            focus (false | true) #REQUIRED
            marks (CDATA) #IMPLIED
            id_d CDATA "nil"
  >
  <!ATTLIST monad_set >
  <!ATTLIST mse
            first CDATA #REQUIRED
            last  CDATA #REQUIRED
  >
  <!ATTLIST feature
            feature_name CDATA #REQUIRED
            feature_type (string|integer|id_d|enum|list_of_integer|list_of_id_d|list_of_enum) #REQUIRED
            enum_type CDATA #IMPLIED 
  >
  <!ELEMENT flatsheaf (flatstraw)* >
  <!ELEMENT flatstraw (matched_object)* >
  <!ATTLIST flatstraw
      object_type_name CDATA #REQUIRED >
]>

<mql_results>
   
   <mql_result>
      <mql_progress>
         
      </mql_progress>
      <sheaf>
         <straw>
            <matched_object object_type_name="chapter" focus="false" id_d="1216766">
               <monad_set>
                  <mse first="358063" last="358358"/>
               </monad_set>
               <sheaf>
                  <straw>
                     <matched_object object_type_name="verse" focus="false" id_d="1217660">
                        <monad_set>
                           <mse first="358154" last="358162"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191906">
                                 <monad_set>
                                    <mse first="358154" last="358154"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217661">
                        <monad_set>
                           <mse first="358163" last="358170"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191915">
                                 <monad_set>
                                    <mse first="358163" last="358163"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217662">
                        <monad_set>
                           <mse first="358171" last="358178"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191923">
                                 <monad_set>
                                    <mse first="358171" last="358171"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217663">
                        <monad_set>
                           <mse first="358179" last="358187"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191931">
                                 <monad_set>
                                    <mse first="358179" last="358179"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217664">
                        <monad_set>
                           <mse first="358188" last="358195"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191940">
                                 <monad_set>
                                    <mse first="358188" last="358188"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217665">
                        <monad_set>
                           <mse first="358196" last="358209"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191948">
                                 <monad_set>
                                    <mse first="358196" last="358196"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217666">
                        <monad_set>
                           <mse first="358210" last="358218"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191962">
                                 <monad_set>
                                    <mse first="358210" last="358210"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217667">
                        <monad_set>
                           <mse first="358219" last="358225"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191971">
                                 <monad_set>
                                    <mse first="358219" last="358219"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217668">
                        <monad_set>
                           <mse first="358226" last="358235"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191978">
                                 <monad_set>
                                    <mse first="358226" last="358226"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217669">
                        <monad_set>
                           <mse first="358236" last="358244"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191988">
                                 <monad_set>
                                    <mse first="358236" last="358236"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217670">
                        <monad_set>
                           <mse first="358245" last="358255"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1191997">
                                 <monad_set>
                                    <mse first="358245" last="358245"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217671">
                        <monad_set>
                           <mse first="358256" last="358266"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192008">
                                 <monad_set>
                                    <mse first="358256" last="358256"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217672">
                        <monad_set>
                           <mse first="358267" last="358273"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192019">
                                 <monad_set>
                                    <mse first="358267" last="358267"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217673">
                        <monad_set>
                           <mse first="358274" last="358283"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192026">
                                 <monad_set>
                                    <mse first="358274" last="358274"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217674">
                        <monad_set>
                           <mse first="358284" last="358293"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192036">
                                 <monad_set>
                                    <mse first="358284" last="358284"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217675">
                        <monad_set>
                           <mse first="358294" last="358302"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192046">
                                 <monad_set>
                                    <mse first="358294" last="358294"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217676">
                        <monad_set>
                           <mse first="358303" last="358311"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192055">
                                 <monad_set>
                                    <mse first="358303" last="358303"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217677">
                        <monad_set>
                           <mse first="358312" last="358319"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192064">
                                 <monad_set>
                                    <mse first="358312" last="358312"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217678">
                        <monad_set>
                           <mse first="358320" last="358326"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192072">
                                 <monad_set>
                                    <mse first="358320" last="358320"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217679">
                        <monad_set>
                           <mse first="358327" last="358335"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192079">
                                 <monad_set>
                                    <mse first="358327" last="358327"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217680">
                        <monad_set>
                           <mse first="358336" last="358347"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192088">
                                 <monad_set>
                                    <mse first="358336" last="358336"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1217681">
                        <monad_set>
                           <mse first="358348" last="358358"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1192100">
                                 <monad_set>
                                    <mse first="358348" last="358348"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                  </straw>
               </sheaf>
            </matched_object>
         </straw>
         <straw>
            <matched_object object_type_name="chapter" focus="false" id_d="1254000">
               <monad_set>
                  <mse first="366500" last="366954"/>
               </monad_set>
               <sheaf>
                  <straw>
                     <matched_object object_type_name="verse" focus="false" id_d="1254005">
                        <monad_set>
                           <mse first="366500" last="366520"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246815">
                                 <monad_set>
                                    <mse first="366500" last="366500"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246824">
                                 <monad_set>
                                    <mse first="366509" last="366509"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254006">
                        <monad_set>
                           <mse first="366521" last="366543"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246836">
                                 <monad_set>
                                    <mse first="366521" last="366521"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254007">
                        <monad_set>
                           <mse first="366544" last="366565"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246859">
                                 <monad_set>
                                    <mse first="366544" last="366544"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254008">
                        <monad_set>
                           <mse first="366566" last="366583"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246881">
                                 <monad_set>
                                    <mse first="366566" last="366566"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254009">
                        <monad_set>
                           <mse first="366584" last="366601"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246899">
                                 <monad_set>
                                    <mse first="366584" last="366584"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254010">
                        <monad_set>
                           <mse first="366602" last="366623"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246917">
                                 <monad_set>
                                    <mse first="366602" last="366602"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254011">
                        <monad_set>
                           <mse first="366624" last="366651"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246939">
                                 <monad_set>
                                    <mse first="366624" last="366624"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254012">
                        <monad_set>
                           <mse first="366652" last="366671"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246967">
                                 <monad_set>
                                    <mse first="366652" last="366652"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254013">
                        <monad_set>
                           <mse first="366672" last="366690"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1246987">
                                 <monad_set>
                                    <mse first="366672" last="366672"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254014">
                        <monad_set>
                           <mse first="366691" last="366709"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1247006">
                                 <monad_set>
                                    <mse first="366691" last="366691"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>
                     <matched_object object_type_name="verse" focus="false" id_d="1254015">
                        <monad_set>
                           <mse first="366710" last="366728"/>
                        </monad_set>
                        <sheaf>
                           <straw>
                              <matched_object object_type_name="word" focus="true" id_d="1247025">
                                 <monad_set>
                                    <mse first="366710" last="366710"/>
                                 </monad_set>
                                 <sheaf>
                                 </sheaf>
                              </matched_object>
                           </straw>
                        </sheaf>
                     </matched_object>